### ISSUE TITLE
Create New Chakra Theme Based of Figma's Design System

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#165]
The design system at https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=173%3A2 already contains 

- Colors
- Typography
- Buttons
- Spacing
- Layout

I will modify Chakra's Theme to match these properties. This should make it easier to fast-track development going forward and maintain consistency.

In the meantime, development will halt for a bit until we figure out the design perfectly.

**Comment by with-heart** [comment]
I think we should start with a single PR for each _token_ (color, typography, spacing) and then move on to more complex pieces like buttons and layout.

Additionally I think we should set some expectations about what it means to _implement_ the token so that merging the PR means we end up with a token that exists in our Chakra theme and is documented well.

@angeljgomezc would you mind if I edit this issue and break it up into a few separate issues to capture this?

**Comment by angeljgomezc** [comment]
> I think we should start with a single PR for each _token_ (color, typography, spacing) and then move on to more complex pieces like buttons and layout.
> 
> Additionally I think we should set some expectations about what it means to _implement_ the token so that merging the PR means we end up with a token that exists in our Chakra theme and is documented well.
> 
> @angeljgomezc would you mind if I edit this issue and break it up into a few separate issues to capture this?

Not at all!

**Comment by with-heart** [comment]
It was easier to just create a new issue! I'm going to close this one in favor of #171

**Comment by with-heart** [comment]
Just a note, I'll open issues for button and layout as we're ready for it
