### ISSUE TITLE
Proposal: Adding user stories for building up the roadmap

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#33]
As per feedback from @with-heart during the call from last Friday, to build out an MVP we need to setup a clear goal on what we want to achieve, what certain functionalities should be shipped, and know what exactly are we building.

I had a slight conversation with @angeljgomezc and I proposed that we'll use of ["User Stories"]( https://www.atlassian.com/agile/project-management/user-stories ) for defining a set of functionalities that we want to ship for the MVP.

We basically just create a bullet list of single sentences/phrases on what we want to expect or what certain functionalities we want to have in the app 

e.g.
- As a developer I want to browse jobs/gigs that I am interested in
- As a developer I want to setup my profile, upload photo, update my description, username
- As a developer I want to send job applications to job postings
- As a developer I want to create gig postings
- As a company recruiter I want to create job postings
- As a company recruiter I want to receive job applications from developers

Personally I think these would helpful for someone that wants to contribute into the project. 

But if there would be any other suggestions than this, please share it with us we would be happy to learn more about it :)

**Comment by with-heart** [comment]
Yes yes yes yes yes yes yes! I love this issue!

I do want to emphasize the importance of the "[so that]" part of the user story though. It's important to understand _why_ the user wants a feature as much as _what_ the feature is because it helps us make sure the features we build actually accomplish the user's _intent_.

An example:

> As a company recruiter, I want to receive job applications from developers

Solution: Let's create a page that lists every submitted developer application

> As a company recruiter, I want to receive job applications from developers, so that I can hire the most qualified developers with skills relevant to the position

Solution: Let's create a page that lists every submitted developer application. We should order the list so that applications from developers _with skills relevant to the position they're applying for_ are at the top.

Both solutions technically implement the requested feature, but because we've thought about user _intent_, the second solution is likely better for fulfilling the user's needs.

**Comment by carlomigueldy** [comment]
> Yes yes yes yes yes yes yes! I love this issue!
> 
> I do want to emphasize the importance of the "[so that]" part of the user story though. It's important to understand _why_ the user wants a feature as much as _what_ the feature is because it helps us make sure the features we build actually accomplish the user's _intent_.
> 
> An example:
> 
> > As a company recruiter, I want to receive job applications from developers
> 
> Solution: Let's create a page that lists every submitted developer application
> 
> > As a company recruiter, I want to receive job applications from developers, so that I can hire the most qualified developers with skills relevant to the position
> 
> Solution: Let's create a page that lists every submitted developer application. We should order the list so that applications from developers _with skills relevant to the position they're applying for_ are at the top.
> 
> Both solutions technically implement the requested feature, but because we've thought about user _intent_, the second solution is likely better for fulfilling the user's needs.

Thank you so much for the suggestion we've been referring on this when writing up & finalizing the RFC!

**Comment by carlomigueldy** [comment]
Closing this issue now since the RFC has been created.

https://forum.developerdao.com/t/rfc-user-stories-for-dao-job-board/507
